#Hello this plugin is made by OnlineMetlesley.
#If you have any questions or bug reports, please join our discord. https://discord.gg/xAHP8cA

#The message when the bucket fills
Message: '&cYour empty bucket has been filled with Lava'
